=== KINGSLEAGUEG4/KINGSLEAGUE/Lenguaje De Marcas/XML_Ultima_Clasificacion/clasificacion_final.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--LOS IDS SON DE TIPO INTEGER YA QUE EN LA BASE DE DATOS SON AUTOINCREMENTALES-->
  
  <xs:element name="jornada" type="tipoJornada"/>
      <xs:complexType name="tipoJornada">
          <xs:sequence>
                <xs:element name="fecha" type="xs:date" minOccurs="0"/>
                <xs:element name="partido" type="infoPartidos" minOccurs="1" maxOccurs="6"/>
                <xs:element name="fecha_expiracion" type="xs:date"/>
          </xs:sequence>
          <xs:attribute name="id_jornada" type="xs:integer" use="required"/>
          <xs:attribute name="id_temporada" type="xs:integer" use="required"/>
          <xs:attribute name="num_jornada" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="infoPartidos">
        <xs:sequence>
            <xs:element name="equipo_local" type="xs:string" maxOccurs="1"/>
            <xs:element name="equipo_visitante" type="xs:string" maxOccurs="1"/>
            <xs:element name="goles_local" type="tGoles_local"/>
            <xs:element name="goles_visitante" type="tGoles_visitante"/>
            <xs:element name="tipo_partido" type="tTipo_partido"/>
            <xs:element name="hora" type="xs:time" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id_partido" type="xs:integer" use="required"/>
    <xs:attribute name="id_jornada" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="tGoles_local">
        <xs:restriction base="xs:integer">
              <xs:minInclusive value="0"/>
          </xs:restriction>
    </xs:simpleType>

  <xs:simpleType name="tGoles_visitante">
    <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tTipo_partido">
    <xs:restriction base="xs:string">
        <xs:enumeration value="FR"/>
        <xs:enumeration value="PO"/>
    </xs:restriction>
 </xs:simpleType>

</xs:schema>

=== KINGSLEAGUEG4/KINGSLEAGUE/Lenguaje De Marcas/XML_Ultima_Clasificacion/clasficacion_final.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--LOS IDS SON DE TIPO INTEGER YA QUE EN LA BASE DE DATOS SON AUTOINCREMENTALES-->

<!DOCTYPE jornada SYSTEM "clasificacion_final.dtd">

<jornada  xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "clasificacion_final.xsd"  id_jornada="14" id_temporada="1" num_jornada="14">
    
    <fecha>2023-03-26</fecha>
    
    <partido id_partido="73" id_jornada="14">
        <equipo_local>EL BARRIO</equipo_local>
        <equipo_visitante>ANIQUILADORES FC</equipo_visitante>
        
        <goles_local>3</goles_local>
        <goles_visitante>0</goles_visitante>
        
        <tipo_partido>PO</tipo_partido>
        <hora>21:00:00</hora>
      </partido>
      
      <fecha_expiracion>2023-03-27</fecha_expiracion>
    
    </jornada>
