=== KINGSLEAGUEG4/KINGSLEAGUE/Lenguaje De Marcas/XML_Jornadas/KingsLeague_jornadas_DTD.dtd
<!--LOS IDS SON DE TIPO INTEGER YA QUE EN LA BASE DE DATOS SON AUTOINCREMENTALES-->

<!ELEMENT TEMPORADA (FECHA_INICIO,FECHA_FIN,ESTADO,PERIODO,JORNADAS,FECHA_EXPIRACION)>
<!ELEMENT FECHA_INICIO (#PCDATA)>
<!ELEMENT FECHA_FIN (#PCDATA)>
<!ELEMENT ESTADO (#PCDATA)>
<!ELEMENT PERIODO (#PCDATA)>
<!ELEMENT JORNADAS (JORNADA*)>
<!ELEMENT FECHA_EXPIRACION (#PCDATA)>
<!ELEMENT JORNADA (FECHA,PARTIDO*)>
<!ATTLIST JORNADA id_jornada CDATA #REQUIRED
          id_temporada CDATA #REQUIRED
          num_jornada CDATA #REQUIRED>
<!ELEMENT FECHA (#PCDATA)>
<!ELEMENT PARTIDO (EQUIPO_LOCAL,EQUIPO_VISITANTE,GOLES_LOCAL,GOLES_VISITANTE,TIPO_PARTIDO,HORA)>
<!ATTLIST PARTIDO id_partido CDATA #REQUIRED
            id_jornada CDATA #REQUIRED>
<!ELEMENT EQUIPO_LOCAL (#PCDATA)>
<!ELEMENT EQUIPO_VISITANTE (#PCDATA)>
<!ELEMENT GOLES_LOCAL (#PCDATA)>
<!ELEMENT GOLES_VISITANTE (#PCDATA)>
<!ELEMENT TIPO_PARTIDO (#PCDATA)>
<!ELEMENT HORA (#PCDATA)>

=== KINGSLEAGUEG4/KINGSLEAGUE/Lenguaje De Marcas/XML_Jornadas/xml_jornadas.xml
<?xml version="1.0"?>
<!-- <!DOCTYPE TEMPORADA SYSTEM "KingsLeague_jornadas_DTD.dtd"> -->
 <TEMPORADA  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="xml_jornadas_xsd.xsd">
  <FECHA_INICIO>2022-11-12</FECHA_INICIO>
  <FECHA_FIN>2023-03-26</FECHA_FIN>
  <ESTADO>CERRADO</ESTADO>
  <PERIODO>INV</PERIODO>
  <JORNADAS>
   <JORNADA id_jornada="1" id_temporada="1" num_jornada="1">
    <FECHA>2023-01-01</FECHA>
    
     <PARTIDO id_partido="1" id_jornada="1">
      <EQUIPO_LOCAL>RAYO DE BARCELONA</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>1K FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>2</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>20:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="2" id_jornada="1">
      <EQUIPO_LOCAL>KUNISPORTS</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>JIJANTES FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>2</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>21:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="3" id_jornada="1">
      <EQUIPO_LOCAL>EL BARRIO</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PIO FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>0</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>19:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="4" id_jornada="1">
      <EQUIPO_LOCAL>LOS TRONCOS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>XBUYER TEAM</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>3</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>18:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="5" id_jornada="1">
      <EQUIPO_LOCAL>ANIQUILADORES FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>ULTIMATE MOSTOLES</EQUIPO_VISITANTE>
      <GOLES_LOCAL>1</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>22:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="6" id_jornada="1">
      <EQUIPO_LOCAL>SAIYANS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PORCINOS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>4</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>23:00:00.000</HORA>
     </PARTIDO>
    
   </JORNADA>
   <JORNADA id_jornada="2" id_temporada="1" num_jornada="2">
    <FECHA>2023-01-08</FECHA>
    
     <PARTIDO id_partido="7" id_jornada="2">
      <EQUIPO_LOCAL>JIJANTES FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>RAYO DE BARCELONA</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>20:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="8" id_jornada="2">
      <EQUIPO_LOCAL>ULTIMATE MOSTOLES</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>EL BARRIO</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>21:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="9" id_jornada="2">
      <EQUIPO_LOCAL>1K FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>ANIQUILADORES FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>19:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="10" id_jornada="2">
      <EQUIPO_LOCAL>PORCINOS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>LOS TRONCOS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>3</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>18:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="11" id_jornada="2">
      <EQUIPO_LOCAL>XBUYER TEAM</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>KUNISPORTS</EQUIPO_VISITANTE>
      <GOLES_LOCAL>0</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>22:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="12" id_jornada="2">
      <EQUIPO_LOCAL>PIO FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>SAIYANS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>23:00:00.000</HORA>
     </PARTIDO>
    
   </JORNADA>
   <JORNADA id_jornada="3" id_temporada="1" num_jornada="3">
    <FECHA>2023-01-15</FECHA>
    
     <PARTIDO id_partido="13" id_jornada="3">
      <EQUIPO_LOCAL>JIJANTES FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>1K FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>20:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="14" id_jornada="3">
      <EQUIPO_LOCAL>RAYO DE BARCELONA</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>XBUYER TEAM</EQUIPO_VISITANTE>
      <GOLES_LOCAL>2</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>21:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="15" id_jornada="3">
      <EQUIPO_LOCAL>SAIYANS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>ULTIMATE MOSTOLES</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>19:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="16" id_jornada="3">
      <EQUIPO_LOCAL>KUNISPORTS</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PORCINOS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>4</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>18:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="17" id_jornada="3">
      <EQUIPO_LOCAL>LOS TRONCOS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PIO FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>22:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="18" id_jornada="3">
      <EQUIPO_LOCAL>EL BARRIO</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>ANIQUILADORES FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>1</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>23:00:00.000</HORA>
     </PARTIDO>
    
   </JORNADA>
   <JORNADA id_jornada="4" id_temporada="1" num_jornada="4">
    <FECHA>2023-01-22</FECHA>
    
     <PARTIDO id_partido="19" id_jornada="4">
      <EQUIPO_LOCAL>XBUYER TEAM</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>JIJANTES FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>20:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="20" id_jornada="4">
      <EQUIPO_LOCAL>PIO FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>KUNISPORTS</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>21:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="21" id_jornada="4">
      <EQUIPO_LOCAL>1K FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>EL BARRIO</EQUIPO_VISITANTE>
      <GOLES_LOCAL>2</GOLES_LOCAL>
      <GOLES_VISITANTE>5</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>19:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="22" id_jornada="4">
      <EQUIPO_LOCAL>PORCINOS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>RAYO DE BARCELONA</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>18:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="23" id_jornada="4">
      <EQUIPO_LOCAL>ANIQUILADORES FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>SAIYANS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>4</GOLES_LOCAL>
      <GOLES_VISITANTE>3</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>22:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="24" id_jornada="4">
      <EQUIPO_LOCAL>ULTIMATE MOSTOLES</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>LOS TRONCOS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>23:00:00.000</HORA>
     </PARTIDO>
    
   </JORNADA>
   <JORNADA id_jornada="5" id_temporada="1" num_jornada="5">
    <FECHA>2023-02-05</FECHA>
    
     <PARTIDO id_partido="25" id_jornada="5">
      <EQUIPO_LOCAL>XBUYER TEAM</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>1K FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>2</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>20:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="26" id_jornada="5">
      <EQUIPO_LOCAL>SAIYANS FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>EL BARRIO</EQUIPO_VISITANTE>
      <GOLES_LOCAL>1</GOLES_LOCAL>
      <GOLES_VISITANTE>0</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>21:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="27" id_jornada="5">
      <EQUIPO_LOCAL>KUNISPORTS</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>ULTIMATE MOSTOLES</EQUIPO_VISITANTE>
      <GOLES_LOCAL>3</GOLES_LOCAL>
      <GOLES_VISITANTE>1</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>19:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="28" id_jornada="5">
      <EQUIPO_LOCAL>JIJANTES FC</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PORCINOS FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>2</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>18:00:00.000</HORA>
     </PARTIDO>
     <PARTIDO id_partido="29" id_jornada="5">
      <EQUIPO_LOCAL>RAYO DE BARCELONA</EQUIPO_LOCAL>
      <EQUIPO_VISITANTE>PIO FC</EQUIPO_VISITANTE>
      <GOLES_LOCAL>5</GOLES_LOCAL>
      <GOLES_VISITANTE>4</GOLES_VISITANTE>
      <TIPO_PARTIDO>FR</TIPO_PARTIDO>
      <HORA>22:00:00.000</HORA>
     </PARTIDO>
